title: Blog do Charuto
author: Cristiano
email: mavicurcio@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  Nestas páginas iremos contar um pouco da história do charuto

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
